project:
  type: website
  output-dir: docs

website:
  title: "gems bond"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      
format:
  html:
    theme: slate
    css: styles.css
  

editor: visual


